### ISSUE TITLE
Getting Build error with Inesignal

### ISSUE THREAD

**Issue by ajaymalik14** [OneSignal/OneSignal-Gradle-Plugin#134]
I am using Below Plugins and Latest android, cordova and plugin:
cordova-admob-sdk 0.24.1 "AdMob SDK"
cordova-plugin-admob-free 0.27.0 "Cordova AdMob Plugin"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.8 "SocialSharing"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.11.0 "OneSignal Push Notifications"

I am getting below error whenever I try to build:

`Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=C:\Android\platforms (recommended setting)
ANDROID_HOME=C:\Android (DEPRECATED)

BUILD SUCCESSFUL in 5s
? actionable task: ? executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!

> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest
> Task :CordovaLib:processDebugManifest
> Task :app:preDebugBuild
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript
> Task :app:checkDebugManifest
> Task :app:generateDebugBuildConfig
> Task :app:prepareLintJar
> Task :app:generateDebugSources
> Task :CordovaLib:compileDebugRenderscript
> Task :CordovaLib:generateDebugBuildConfig
> Task :CordovaLib:generateDebugResValues
> Task :CordovaLib:generateDebugResources
> Task :CordovaLib:packageDebugResources
> Task :CordovaLib:generateDebugRFile
> Task :CordovaLib:prepareLintJar
> Task :CordovaLib:generateDebugSources
> Task :CordovaLib:javaPreCompileDebug
> Task :CordovaLib:compileDebugJavaWithJavac
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> Task :app:javaPreCompileDebug
> Task :app:mainApkListPersistenceDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:mergeDebugResources FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Users\AJ\Desktop\blogapp\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v२३\values-v२३.xml: error: invalid configuration 'v२३'.

?? actionable tasks: ?? executed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 33s
C:\Users\AJ\Desktop\blogapp\platforms\android\gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  C:\Users\AJ\Desktop\blogapp\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v२३\values-v२३.xml: error: invalid configuration 'v२३'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 33s`

**Comment by jkasten2** [comment]
@ajaymalik14 Could you provide the following details?
1. Cordova version you are using
2. Narrow down the exact plugin the is causing build issue. Can you remove one at a time to find plugin causing the build issue?

**Comment by jkasten2** [comment]
@ajaymalik14 I took a 2nd pass at your log and it seems this is the root cause.
```
java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
C:\Users\AJ\Desktop\blogapp\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v२३\values-v२३.xml: error: invalid configuration 'v२३'.
```

Your file `values-v२३\values-v२३.xml` isn't a valid name for Android. It needs to follow the  two-letter ISO 639-1 language code.
See Android's documentation for more details.
https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources
