### ISSUE TITLE
Failed to apply plugin

### ISSUE THREAD

**Issue by dhwalin** [OneSignal/OneSignal-Gradle-Plugin#152]
After upgrading to gradle 7
```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin class 'com.onesignal.androidsdk.GradleProjectPlugin'.
```
Using Capacitor 3, ReactJS, ionic-native onesignal

**Comment by Gautammer** [comment]
Same isssue! did you found solution?

**Comment by dhwalin** [comment]
Not yet. I have submitted issue to onesignal. Waiting for their reply.

**Comment by crabbydavis** [comment]
Also seeing this error. I'm using Capacitor 3, Angular, and the onesignal-cordova-plugin. Tried 2.11.2, 2.11.3 and 3.0.0-beta1, and got the same error for all three.

**Comment by dhwalin** [comment]
For some packages only I have to switch to Gradle 7. Working in Gradle 6.*.*. So if developers do not need 7 for any other package, they can switch to lower version of gradle.

**Comment by alainm23** [comment]
I'm using `Capacitor 3`, `Ionic 5`, `onesignal-cordova-plugin@2.11.1`, `@ionic-native/onesignal@5.30.0` and I just downgraded to gradle to version 6 and everything worked fine.

File -> Project Structure -> Project

![image](https://user-images.githubusercontent.com/33765137/119711844-994d9d00-be25-11eb-86ff-4beb58d50e59.png)

**Comment by crabbydavis** [comment]
@dhwalin  @alainm23 thanks for the help! My project is running with Gradle 6. Guess I'll run with that until One Signal gets the plugin working with Gradle 7

**Comment by Gautammer** [comment]
Oh i didn’t had time , so i gone with cordova..

**Comment by Elardzhi** [comment]
Works on Gradle 6.9.
Capacitor 3 recommends using Gradle 7. Waiting OneSignal to be updated.

**Comment by ba6ba** [comment]
Are we going to have any update on this. OneSignal Team?

**Comment by jkasten2** [comment]
Thanks for reporting! 
Gradle 7 compatibility has been added in [version 0.13.0](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.13.0).
   - Note, that [version 0.13.4](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.13.4) is recommended however.

This version should automatically be available then next time you do a clean build.
