### ISSUE TITLE
Hola tengo problema con este Error de Onesigna. Alguien Me puede  ayudar ?

### ISSUE THREAD

**Issue by ar170891** [OneSignal/OneSignal-Gradle-Plugin#43]
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {

        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.1, 0.99.99]'
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
   apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
    maven { url 'https://maven.fabric.io/public' }
}

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    signingConfigs {
        debug {
            storeFile file('musicfree.jks')
            keyAlias 'musicfree'
            keyPassword 'musicfree'
            storePassword 'musicfree'
        }
    }

    defaultConfig {
        applicationId "com.toreradio.putnikradiode"

        manifestPlaceholders = [onesignal_app_id: '35ba9fbc-3bff-49bd-812f-da832f8936a3',
                // Project number pulled from dashboard, local value is ignored.
                onesignal_google_project_number: 'REMOTE']

        minSdkVersion 17
        targetSdkVersion 26
        versionCode 1
        versionName "1.0.1"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    /* 4) Exclude duplicate licenses */
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    //for emotion string
    aaptOptions {
        additionalParameters '--utf16'
        additionalParameters "--no-version-vectors"
    }
}

dependencies {
    //implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':equalizerview')
    implementation project(':SeekArc_library')
    implementation 'com.afollestad.material-dialogs:core:0.9.6.0'
    implementation 'com.android.support:multidex:1.0.2'

    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.android.support:customtabs:27.1.1'
    implementation 'com.android.support:support-v13:27.1.1'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.android.support:exifinterface:27.1.1'
    implementation 'com.android.support:support-vector-drawable:27.1.1'
    implementation 'com.onesignal:OneSignal:[3.9.1, 3.99.99]'
    implementation 'com.google.android.gms:play-services-ads:15.0.0'
    implementation 'com.google.android.gms:play-services-gcm:15.0.0'
    implementation 'com.google.android.gms:play-services-location:15.0.0'
    implementation 'com.google.firebase:firebase-config:15.0.0'
    implementation 'com.google.firebase:firebase-core:15.0.0'

    implementation 'com.google.code.gson:gson:2.8.2'
    implementation 'com.squareup.okio:okio:1.14.0'
    implementation 'com.github.hotchemi:android-rate:1.0.1'
    implementation 'jp.wasabeef:glide-transformations:2.0.2'
    implementation 'com.balysv:material-ripple:1.0.2'
    implementation 'com.squareup.okhttp3:okhttp:3.8.0'
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation 'com.github.jd-alexander:LikeButton:0.2.3'
    implementation 'com.facebook.android:audience-network-sdk:4.28.1'
    implementation 'com.github.warkiz.widget:indicatorseekbar:1.2.9'
    implementation 'com.wang.avi:library:2.1.3'
    compile('com.crashlytics.sdk.android:crashlytics:2.9.3@aar') {
        transitive = true;
    }

}
apply plugin: 'com.google.gms.google-services'

**Comment by jkasten2** [comment]
@ar170891 This is duplicated ticket. Closing in favor of #44 since you provide a bit more details in the title there.
