### ISSUE TITLE
What does 'not found in maxSupportVersion' warning mean?

### ISSUE THREAD

**Issue by jahirfiquitiva** [OneSignal/OneSignal-Gradle-Plugin#54]
### Project Setup
`app/build.gradle`
```Gradle
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.11.0'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

dependencies {
    implementation 'com.onesignal:OneSignal:3.9.3'
}
```

### Logs
```Gradle
OneSignalPlugin: 28 not found in maxSupportVersion rules list.
Assuming max safe default of '28.+' for 'com.android.support'
```

**Comment by jkasten2** [comment]
@jahirfiquitiva This warning means that we haven't defined a maximum Android Support Library for   `compileSDKVersion 28` yet. It falling back to `'28.+'` as a safe default which is correct in this case.

We will add this to the version list in the next version so this warning will not show in the future.

**Comment by jahirfiquitiva** [comment]
Is it safe or ok to keep using this version in the meantime? Or I must downgrade the `compileSDKVersion`?

**Comment by jkasten2** [comment]
@jahirfiquitiva Yes, it is safe to ignore this warning. The correct version of the Android Support Library is being used in this case
