### ISSUE TITLE
NPE - From detectProjectState -> compareVersions

### ISSUE THREAD

**Issue by 2x2xplz** [OneSignal/OneSignal-Gradle-Plugin#55]
I'm upgrading from an older version of OneSignal where all the config was done manually by editing the manifest, added GCM manually, etc. Now I'm on Android Studio 3.0.1 with Gradle 4.4 and com.android.tools.build:gradle:3.1.3 (also I had to enable multidex) and cannot get the plugin installed:
```java
Caused by: java.lang.NullPointerException
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionParser.transform(VersionParser.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionParser.transform(VersionParser.java:25)
        at org.gradle.api.Transformer$transform.call(Unknown Source)
        at com.onesignal.androidsdk.GradleProjectPlugin.compareVersions(GradleProjectPlugin.groovy:456)
        at com.onesignal.androidsdk.GradleProjectPlugin$compareVersions$0.callStatic(Unknown Source)
        at com.onesignal.androidsdk.GradleProjectPlugin.detectProjectState(GradleProjectPlugin.groovy:201)
        at com.onesignal.androidsdk.GradleProjectPlugin.apply(GradleProjectPlugin.groovy:167)
        at com.onesignal.androidsdk.GradleProjectPlugin.apply(GradleProjectPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:165)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
        ... 103 more
```
2 things:
1) other plugins load fine, not sure why this one doesn't
2) I liked doing the config by hand -- I have no idea what your plugin does and would prefer to do it manually, it's not that hard and I would feel better knowing what you are adding to my app.

also:
```gradle
    compileSdkVersion 27
    buildToolsVersion '28.0.1'
    multiDexEnabled true
```

**Comment by jkasten2** [comment]
@2x2xplz Thanks for reproducing the stacktrace. Can you provide your `build.gradle` so we can try reproducing the issue with it?

This plugin at a high level makes sure compatible versions of `com.google.android.gms`, `com.google.firebase`, and `com.android.support` are used by either downgrading or upgrading these versions automatically. Running `./gradlew app:dependencies` will give you the finial dependency tree. Adding `--info` to the end of this command will show OneSignal log entries if it changes any versions along the way. The [readme](https://github.com/OneSignal/OneSignal-Gradle-Plugin/blob/master/README.md) goes into more details

This plugin may not be required if there are no conflicting versions issues so adding the OneSignal Android SDK with the following may work just fine.
```gradle
dependencies {
    implementation 'com.onesignal:OneSignal:[3.9.3, 3.99.99]'
}
```

If the above creates a compile or runtime crash with android support, firebase, or google play services then the above most likely caused Gradle to pull in a mixture of incompatible versions. Adding `@aar` can then be used instead to omit OneSignal's dependencies.
```gradle
dependencies {
    implementation 'com.onesignal:OneSignal:3.9.3@aar'
}
```

However you will also need to add it's dependencies too and set them to a version that is compatible with it and the rest of your project.

```gradle
dependencies {
    implementation 'com.onesignal:OneSignal:3.9.3@aar'

    // These are the dependencies and version ranges for the specific version above
    implementation 'com.android.support:support-v4:[26.0.0, 27.2.0)'
    implementation 'com.android.support:customtabs:[26.0.0, 27.2.0)'
    implementation 'com.google.firebase:firebase-messaging:[10.2.1, 12.1.0)'
    implementation 'com.google.android.gms:play-services-location:[10.2.1, 12.1.0)'
    implementation 'com.google.android.gms:play-services-base:[10.2.1, 12.1.0)'
}
```

For`com.android.support` above to the same version number you use else where in your `build.gradle`.
For `com.google.firebase` and `com.google.android.gms` this is a bit tricker. If you used versions before 15 you will need to make sure all these versions match exactly. If you use 15 or newer for any of them then they must all be 15+. Google has more details on their doc here
https://developers.google.com/android/guides/versioning

**Comment by jkasten2** [comment]
@2x2xplz I see, can you still provide your `build.gradle` so we can reproduce this issue?

As long as you are not using a local `OneSignalSDK.jar` file then you won't have to touch your `AndroidManifest.xml` for a basic setup.

In your case you can remove the top 3 `<use-permission ...>` tags. The other ones you need to keep as those are override settings for OneSignal. Expect for the `<receiver ...>` tag you have `InstallBroadcastReceiver` or `INSTALL_REFERRER ` isn't something OneSignal uses.

**Comment by 2x2xplz** [comment]
Again, thank you for the replies. OK I may have have figured it out. Your plugin must be first, before Android and before Kotlin. It did compile when I moved it. However those plugins say they need to be at the top. This is my issue with these plugins. If it can't run independently, I have to assume its because it is making some underlying changes or relying on specific settings. If your plugin fails because of some adjustment that the Android or Kotlin plugin makes, it isn't independent.

Nothing personal, but Android and Kotlin are more important than OneSignal so if they say they need to be first, I'm placing them first.

Here's the top of my build.gradle, this will fail:

```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

apply plugin: 'io.github.http-builder-ng.http-plugin'  // performs the metadata validation and checkin via HTTP

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

But if I move your plugin to the top, yes it seems to compile. (It won't compile even if I move it to 2nd position).

**Comment by jkasten2** [comment]
@2x2xplz `onesignal-gradle-plugin` should work either before orafter `com.android.application`. I haven't tested the other plugins so I can't say for sure if their could be any issues but I won't think so.

Which version fo the AGP (Android Gradle Plugin) are you using? This would be in your root level `build.gradle` file under `buildscripts`. Look for `com.android.tools.build:gradle`.
```gradle
buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        // This should be 3.0.0 or newer for best compatibility
        classpath 'com.android.tools.build:gradle:3.1.3'
    }
}
```

Version 3.0.0+ is needed so the order won't cause any issues. Since you are using newer `compileSDKVersion` and `buildToolsVersion` I am guess you have updated this already but please confirm just in case.

**Comment by 2x2xplz** [comment]
Yes, plugin 3.1.3.
Android Studio 3.0.1 on Windows 7 64bit.
Gradle version 4.4
The error is "Failed to apply plugin"

```
buildscript {
    ext.kotlin_version = '1.2.41'
    repositories {
        google()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.0.2' // 4.0.1
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

**Comment by jkasten2** [comment]
@2x2xplz Thanks for the details, we will try to reproduce this with what you provided.
