### ISSUE TITLE
Re: id com.onesignal.androidsdk.onesignal-gradle-plugin not found

### ISSUE THREAD

**Issue by max-pro** [OneSignal/OneSignal-Gradle-Plugin#86]
hello All,
I'm new to android here is my app.gradle file. always getting error id com.onesignal.androidsdk.onesignal-gradle-plugin not found

buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}

android {
  defaultConfig {  
    generatedDensities = []
    applicationId = "com.example"
    manifestPlaceholders = [
          onesignal_app_id: '',
          // Project number pulled from dashboard, local value is ignored.
          onesignal_google_project_number: 'REMOTE'
      ]
  }
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
}

dependencies {
    implementation 'com.onesignal:OneSignal:[3.9.1, 3.99.99]'
}

**Comment by retyui** [comment]
I have the same problem:
```sh
   > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99].
     Required by:
         project :
      > Failed to list versions for gradle.plugin.com.onesignal:onesignal-gradle-plugin.
         > Unable to load Maven meta-data from https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml.
            > Could not HEAD 'https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml'. Received status code 500 from server: Internal Server Error
```

**Comment by erhanbicer** [comment]
i have the same problem

```
* What went wrong:
A problem occurred configuring root project 'BalikYe'.
> Could not resolve all files for configuration ':classpath'.

  > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99].
     Required by:
         project :
      > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99].
         > Failed to list versions for gradle.plugin.com.onesignal:onesignal-gradle-plugin.
            > Unable to load Maven meta-data from https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml.
               > Could not HEAD 'https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml'. Received status code 500 from server: Internal Server Error

```

**Comment by erhanbicer** [comment]
i have the same problem

```
* What went wrong:
A problem occurred configuring root project
> Could not resolve all files for configuration ':classpath'.

  > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99].
     Required by:
         project :
      > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99].
         > Failed to list versions for gradle.plugin.com.onesignal:onesignal-gradle-plugin.
            > Unable to load Maven meta-data from https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml.
               > Could not HEAD 'https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml'. Received status code 500 from server: Internal Server Error

```

**Comment by laimonas** [comment]
Same issue to me:

* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not resolve all files for configuration 'classpath'.
   > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99].
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99].
         > Failed to list versions for gradle.plugin.com.onesignal:onesignal-gradle-plugin.
            > Unable to load Maven meta-data from https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml.
               > Could not HEAD 'https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml'. Received status code 500 from server: Internal Server Error

**Comment by erhanbicer** [comment]
problem is solved

**Comment by eviliana** [comment]
Same here. I don't think it's related to onesignal, looks like Plugin portal has issues [https://status.gradle.com/](https://status.gradle.com/)

**Comment by jkasten2** [comment]
@eviliana Thanks for linking the status here. It is seems Gradle's servers are operational now, closing this issue.

**Comment by wvansl** [comment]
It is working now!

**Comment by max-pro** [comment]
Thanks,But how to asyn gradle in nativescript instead of removing platform and node_module
