### ISSUE TITLE
Android Q API Level 29

### ISSUE THREAD

**Issue by iNoles** [OneSignal/OneSignal-Gradle-Plugin#92]
I get this message from the Gradle Console is
OneSignalPlugin: 29 not found in maxSupportVersion rules list.
Assuming max safe default of '29.+' for 'com.android.support'

There is no com.android.support versions for 29 because it is now AndroidX. 

I am using the latest versions of the OneSignal Gradle Plugin.

**Comment by jerearaujo03** [comment]
Did you solve it?

**Comment by jkasten2** [comment]
@iNoles @jerearaujo03 Thanks for reporting! This is now fixed in 0.12.3
https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.12.3
