### ISSUE TITLE
Does it work with Unity?

### ISSUE THREAD

**Issue by zenith-jacob** [OneSignal/OneSignal-Gradle-Plugin#99]
Does it work with Unity?
If so, is the integration the same, as in the native Android? Using mainTemplate.gradle?

**Comment by jkasten2** [comment]
@zenith-jacob Thanks for the suggestion. This plugin now works as of version 0.12.3 with Unity. We now have this part of our documentation.
https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility
